// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	_value_objects "s21_rogue/internal/domain/value_objects"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson70e2e50dDecodeS21RogueInternalDomainDto(in *jlexer.Lexer, out *PlaygroundDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "dungeon":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto1(in, &out.DungeonDTO)
		case "character":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto2(in, &out.CharacterDTO)
		case "backpack":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto3(in, &out.BackpackDTO)
		case "monsters":
			if in.IsNull() {
				in.Skip()
				out.MonstersDTO = nil
			} else {
				in.Delim('[')
				if out.MonstersDTO == nil {
					if !in.IsDelim(']') {
						out.MonstersDTO = make([]MonsterDTO, 0, 2)
					} else {
						out.MonstersDTO = []MonsterDTO{}
					}
				} else {
					out.MonstersDTO = (out.MonstersDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v1 MonsterDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto4(in, &v1)
					out.MonstersDTO = append(out.MonstersDTO, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "foods":
			if in.IsNull() {
				in.Skip()
				out.FoodsDTO = nil
			} else {
				in.Delim('[')
				if out.FoodsDTO == nil {
					if !in.IsDelim(']') {
						out.FoodsDTO = make([]FoodPositionDTO, 0, 1)
					} else {
						out.FoodsDTO = []FoodPositionDTO{}
					}
				} else {
					out.FoodsDTO = (out.FoodsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v2 FoodPositionDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto5(in, &v2)
					out.FoodsDTO = append(out.FoodsDTO, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "scrolls":
			if in.IsNull() {
				in.Skip()
				out.ScrollsDTO = nil
			} else {
				in.Delim('[')
				if out.ScrollsDTO == nil {
					if !in.IsDelim(']') {
						out.ScrollsDTO = make([]ScrollPositionDTO, 0, 0)
					} else {
						out.ScrollsDTO = []ScrollPositionDTO{}
					}
				} else {
					out.ScrollsDTO = (out.ScrollsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v3 ScrollPositionDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto6(in, &v3)
					out.ScrollsDTO = append(out.ScrollsDTO, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "elixirs":
			if in.IsNull() {
				in.Skip()
				out.ElixirsDTO = nil
			} else {
				in.Delim('[')
				if out.ElixirsDTO == nil {
					if !in.IsDelim(']') {
						out.ElixirsDTO = make([]ElixirPositionDTO, 0, 0)
					} else {
						out.ElixirsDTO = []ElixirPositionDTO{}
					}
				} else {
					out.ElixirsDTO = (out.ElixirsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ElixirPositionDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto7(in, &v4)
					out.ElixirsDTO = append(out.ElixirsDTO, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "weapons":
			if in.IsNull() {
				in.Skip()
				out.WeaponsDTO = nil
			} else {
				in.Delim('[')
				if out.WeaponsDTO == nil {
					if !in.IsDelim(']') {
						out.WeaponsDTO = make([]WeaponPositionDTO, 0, 1)
					} else {
						out.WeaponsDTO = []WeaponPositionDTO{}
					}
				} else {
					out.WeaponsDTO = (out.WeaponsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v5 WeaponPositionDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto8(in, &v5)
					out.WeaponsDTO = append(out.WeaponsDTO, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "treasure":
			if in.IsNull() {
				in.Skip()
				out.TreasuresDTO = nil
			} else {
				in.Delim('[')
				if out.TreasuresDTO == nil {
					if !in.IsDelim(']') {
						out.TreasuresDTO = make([]TreasurePositionDTO, 0, 1)
					} else {
						out.TreasuresDTO = []TreasurePositionDTO{}
					}
				} else {
					out.TreasuresDTO = (out.TreasuresDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v6 TreasurePositionDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto9(in, &v6)
					out.TreasuresDTO = append(out.TreasuresDTO, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto(out *jwriter.Writer, in PlaygroundDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"dungeon\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainDto1(out, in.DungeonDTO)
	}
	{
		const prefix string = ",\"character\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainDto2(out, in.CharacterDTO)
	}
	{
		const prefix string = ",\"backpack\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainDto3(out, in.BackpackDTO)
	}
	{
		const prefix string = ",\"monsters\":"
		out.RawString(prefix)
		if in.MonstersDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.MonstersDTO {
				if v7 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto4(out, v8)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"foods\":"
		out.RawString(prefix)
		if in.FoodsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.FoodsDTO {
				if v9 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto5(out, v10)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"scrolls\":"
		out.RawString(prefix)
		if in.ScrollsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.ScrollsDTO {
				if v11 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto6(out, v12)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"elixirs\":"
		out.RawString(prefix)
		if in.ElixirsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v13, v14 := range in.ElixirsDTO {
				if v13 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto7(out, v14)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"weapons\":"
		out.RawString(prefix)
		if in.WeaponsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.WeaponsDTO {
				if v15 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto8(out, v16)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"treasure\":"
		out.RawString(prefix)
		if in.TreasuresDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.TreasuresDTO {
				if v17 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto9(out, v18)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PlaygroundDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson70e2e50dEncodeS21RogueInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PlaygroundDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson70e2e50dEncodeS21RogueInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PlaygroundDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson70e2e50dDecodeS21RogueInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PlaygroundDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson70e2e50dDecodeS21RogueInternalDomainDto(l, v)
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto9(in *jlexer.Lexer, out *TreasurePositionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "treasure":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto10(in, &out.TreasureDTO)
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto9(out *jwriter.Writer, in TreasurePositionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"treasure\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainDto10(out, in.TreasureDTO)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in *jlexer.Lexer, out *_value_objects.Position) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.X = int(in.Int())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Y = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out *jwriter.Writer, in _value_objects.Position) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Int(int(in.X))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Int(int(in.Y))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto10(in *jlexer.Lexer, out *TreasureDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "score":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Score = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto10(out *jwriter.Writer, in TreasureDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"score\":"
		out.RawString(prefix)
		out.Int(int(in.Score))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto8(in *jlexer.Lexer, out *WeaponPositionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "weapon":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto11(in, &out.WeaponDTO)
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto8(out *jwriter.Writer, in WeaponPositionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"weapon\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainDto11(out, in.WeaponDTO)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto11(in *jlexer.Lexer, out *WeaponDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "strength":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Strength = int(in.Int())
			}
		case "selected":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Selected = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto11(out *jwriter.Writer, in WeaponDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"strength\":"
		out.RawString(prefix)
		out.Int(int(in.Strength))
	}
	{
		const prefix string = ",\"selected\":"
		out.RawString(prefix)
		out.Bool(bool(in.Selected))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto7(in *jlexer.Lexer, out *ElixirPositionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "elixir":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto12(in, &out.ElixirDTO)
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto7(out *jwriter.Writer, in ElixirPositionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"elixir\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainDto12(out, in.ElixirDTO)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto12(in *jlexer.Lexer, out *ElixirDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "boost_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BoostType = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		case "steps":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountSteps = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto12(out *jwriter.Writer, in ElixirDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"boost_type\":"
		out.RawString(prefix)
		out.String(string(in.BoostType))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	{
		const prefix string = ",\"steps\":"
		out.RawString(prefix)
		out.Int(int(in.CountSteps))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto6(in *jlexer.Lexer, out *ScrollPositionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "scroll":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto13(in, &out.ScrollDTO)
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto6(out *jwriter.Writer, in ScrollPositionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"scroll\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainDto13(out, in.ScrollDTO)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto13(in *jlexer.Lexer, out *ScrollDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "boost_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BoostType = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto13(out *jwriter.Writer, in ScrollDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"boost_type\":"
		out.RawString(prefix)
		out.String(string(in.BoostType))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.Int(int(in.Value))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto5(in *jlexer.Lexer, out *FoodPositionDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "food":
			easyjson70e2e50dDecodeS21RogueInternalDomainDto14(in, &out.FoodDTO)
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto5(out *jwriter.Writer, in FoodPositionDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"food\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainDto14(out, in.FoodDTO)
	}
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto14(in *jlexer.Lexer, out *FoodDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UUID = string(in.String())
			}
		case "label":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Label = string(in.String())
			}
		case "health":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Health = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto14(out *jwriter.Writer, in FoodDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"health\":"
		out.RawString(prefix)
		out.Int(int(in.Health))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto4(in *jlexer.Lexer, out *MonsterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "position":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		case "monster_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MonsterTypeDTO = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto4(out *jwriter.Writer, in MonsterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	{
		const prefix string = ",\"monster_type\":"
		out.RawString(prefix)
		out.String(string(in.MonsterTypeDTO))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto3(in *jlexer.Lexer, out *BackpackDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "foods":
			if in.IsNull() {
				in.Skip()
				out.FoodsDTO = nil
			} else {
				in.Delim('[')
				if out.FoodsDTO == nil {
					if !in.IsDelim(']') {
						out.FoodsDTO = make([]FoodDTO, 0, 1)
					} else {
						out.FoodsDTO = []FoodDTO{}
					}
				} else {
					out.FoodsDTO = (out.FoodsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v19 FoodDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto14(in, &v19)
					out.FoodsDTO = append(out.FoodsDTO, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "scrolls":
			if in.IsNull() {
				in.Skip()
				out.ScrollsDTO = nil
			} else {
				in.Delim('[')
				if out.ScrollsDTO == nil {
					if !in.IsDelim(']') {
						out.ScrollsDTO = make([]ScrollDTO, 0, 1)
					} else {
						out.ScrollsDTO = []ScrollDTO{}
					}
				} else {
					out.ScrollsDTO = (out.ScrollsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v20 ScrollDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto13(in, &v20)
					out.ScrollsDTO = append(out.ScrollsDTO, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "elixirs":
			if in.IsNull() {
				in.Skip()
				out.ElixirsDTO = nil
			} else {
				in.Delim('[')
				if out.ElixirsDTO == nil {
					if !in.IsDelim(']') {
						out.ElixirsDTO = make([]ElixirDTO, 0, 1)
					} else {
						out.ElixirsDTO = []ElixirDTO{}
					}
				} else {
					out.ElixirsDTO = (out.ElixirsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v21 ElixirDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto12(in, &v21)
					out.ElixirsDTO = append(out.ElixirsDTO, v21)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "weapons":
			if in.IsNull() {
				in.Skip()
				out.WeaponsDTO = nil
			} else {
				in.Delim('[')
				if out.WeaponsDTO == nil {
					if !in.IsDelim(']') {
						out.WeaponsDTO = make([]WeaponDTO, 0, 1)
					} else {
						out.WeaponsDTO = []WeaponDTO{}
					}
				} else {
					out.WeaponsDTO = (out.WeaponsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v22 WeaponDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto11(in, &v22)
					out.WeaponsDTO = append(out.WeaponsDTO, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "treasures":
			if in.IsNull() {
				in.Skip()
				out.TreasuresDTO = nil
			} else {
				in.Delim('[')
				if out.TreasuresDTO == nil {
					if !in.IsDelim(']') {
						out.TreasuresDTO = make([]TreasureDTO, 0, 1)
					} else {
						out.TreasuresDTO = []TreasureDTO{}
					}
				} else {
					out.TreasuresDTO = (out.TreasuresDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v23 TreasureDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto10(in, &v23)
					out.TreasuresDTO = append(out.TreasuresDTO, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto3(out *jwriter.Writer, in BackpackDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"foods\":"
		out.RawString(prefix[1:])
		if in.FoodsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.FoodsDTO {
				if v24 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto14(out, v25)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"scrolls\":"
		out.RawString(prefix)
		if in.ScrollsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.ScrollsDTO {
				if v26 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto13(out, v27)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"elixirs\":"
		out.RawString(prefix)
		if in.ElixirsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.ElixirsDTO {
				if v28 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto12(out, v29)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"weapons\":"
		out.RawString(prefix)
		if in.WeaponsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v30, v31 := range in.WeaponsDTO {
				if v30 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto11(out, v31)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"treasures\":"
		out.RawString(prefix)
		if in.TreasuresDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.TreasuresDTO {
				if v32 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto10(out, v33)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto2(in *jlexer.Lexer, out *CharacterDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rooms":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Position)
		case "current_health":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentHealth = int(in.Int())
			}
		case "max_health":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxHealth = int(in.Int())
			}
		case "agile":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Agile = int(in.Int())
			}
		case "strength":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Strength = int(in.Int())
			}
		case "boosts":
			if in.IsNull() {
				in.Skip()
				out.Boosts = nil
			} else {
				in.Delim('[')
				if out.Boosts == nil {
					if !in.IsDelim(']') {
						out.Boosts = make([]BoostValue, 0, 2)
					} else {
						out.Boosts = []BoostValue{}
					}
				} else {
					out.Boosts = (out.Boosts)[:0]
				}
				for !in.IsDelim(']') {
					var v34 BoostValue
					easyjson70e2e50dDecodeS21RogueInternalDomainDto15(in, &v34)
					out.Boosts = append(out.Boosts, v34)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto2(out *jwriter.Writer, in CharacterDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Position)
	}
	{
		const prefix string = ",\"current_health\":"
		out.RawString(prefix)
		out.Int(int(in.CurrentHealth))
	}
	{
		const prefix string = ",\"max_health\":"
		out.RawString(prefix)
		out.Int(int(in.MaxHealth))
	}
	{
		const prefix string = ",\"agile\":"
		out.RawString(prefix)
		out.Int(int(in.Agile))
	}
	{
		const prefix string = ",\"strength\":"
		out.RawString(prefix)
		out.Int(int(in.Strength))
	}
	{
		const prefix string = ",\"boosts\":"
		out.RawString(prefix)
		if in.Boosts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.Boosts {
				if v35 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto15(out, v36)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto15(in *jlexer.Lexer, out *BoostValue) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "boost_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BoostType = string(in.String())
			}
		case "boost_value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BoostValue = int(in.Int())
			}
		case "count_steps":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountSteps = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto15(out *jwriter.Writer, in BoostValue) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"boost_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.BoostType))
	}
	{
		const prefix string = ",\"boost_value\":"
		out.RawString(prefix)
		out.Int(int(in.BoostValue))
	}
	{
		const prefix string = ",\"count_steps\":"
		out.RawString(prefix)
		out.Int(int(in.CountSteps))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto1(in *jlexer.Lexer, out *DungeonDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rooms":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v37 := 0
				for !in.IsDelim(']') {
					if v37 < 3 {
						if in.IsNull() {
							in.Skip()
						} else {
							in.Delim('[')
							v38 := 0
							for !in.IsDelim(']') {
								if v38 < 3 {
									easyjson70e2e50dDecodeS21RogueInternalDomainDto16(in, &((out.Rooms)[v37])[v38])
									v38++
								} else {
									in.SkipRecursive()
								}
								in.WantComma()
							}
							in.Delim(']')
						}
						v37++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "corridors":
			if in.IsNull() {
				in.Skip()
				out.CorridorsDTO = nil
			} else {
				in.Delim('[')
				if out.CorridorsDTO == nil {
					if !in.IsDelim(']') {
						out.CorridorsDTO = make([]CorridorDTO, 0, 0)
					} else {
						out.CorridorsDTO = []CorridorDTO{}
					}
				} else {
					out.CorridorsDTO = (out.CorridorsDTO)[:0]
				}
				for !in.IsDelim(']') {
					var v39 CorridorDTO
					easyjson70e2e50dDecodeS21RogueInternalDomainDto17(in, &v39)
					out.CorridorsDTO = append(out.CorridorsDTO, v39)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "portal":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.Portal)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto1(out *jwriter.Writer, in DungeonDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rooms\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v40 := range in.Rooms {
			if v40 > 0 {
				out.RawByte(',')
			}
			out.RawByte('[')
			for v41 := range (in.Rooms)[v40] {
				if v41 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto16(out, ((in.Rooms)[v40])[v41])
			}
			out.RawByte(']')
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"corridors\":"
		out.RawString(prefix)
		if in.CorridorsDTO == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v42, v43 := range in.CorridorsDTO {
				if v42 > 0 {
					out.RawByte(',')
				}
				easyjson70e2e50dEncodeS21RogueInternalDomainDto17(out, v43)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"portal\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.Portal)
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto17(in *jlexer.Lexer, out *CorridorDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "position":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v44 := 0
				for !in.IsDelim(']') {
					if v44 < 4 {
						easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &(out.Positions)[v44])
						v44++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "visited_state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VisitStateDTO = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto17(out *jwriter.Writer, in CorridorDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"position\":"
		out.RawString(prefix[1:])
		out.RawByte('[')
		for v45 := range in.Positions {
			if v45 > 0 {
				out.RawByte(',')
			}
			easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, (in.Positions)[v45])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"visited_state\":"
		out.RawString(prefix)
		out.String(string(in.VisitStateDTO))
	}
	out.RawByte('}')
}
func easyjson70e2e50dDecodeS21RogueInternalDomainDto16(in *jlexer.Lexer, out *RoomDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "top_left":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.TopLeft)
		case "bot_right":
			easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &out.BotRight)
		case "doors":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('[')
				v46 := 0
				for !in.IsDelim(']') {
					if v46 < 4 {
						easyjson70e2e50dDecodeS21RogueInternalDomainValueObjects(in, &(out.Doors)[v46])
						v46++
					} else {
						in.SkipRecursive()
					}
					in.WantComma()
				}
				in.Delim(']')
			}
		case "visited_state":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VisitStateDTO = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson70e2e50dEncodeS21RogueInternalDomainDto16(out *jwriter.Writer, in RoomDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"top_left\":"
		out.RawString(prefix[1:])
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.TopLeft)
	}
	{
		const prefix string = ",\"bot_right\":"
		out.RawString(prefix)
		easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, in.BotRight)
	}
	{
		const prefix string = ",\"doors\":"
		out.RawString(prefix)
		out.RawByte('[')
		for v47 := range in.Doors {
			if v47 > 0 {
				out.RawByte(',')
			}
			easyjson70e2e50dEncodeS21RogueInternalDomainValueObjects(out, (in.Doors)[v47])
		}
		out.RawByte(']')
	}
	{
		const prefix string = ",\"visited_state\":"
		out.RawString(prefix)
		out.String(string(in.VisitStateDTO))
	}
	out.RawByte('}')
}
