// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCd10493DecodeS21RogueInternalDomainDto(in *jlexer.Lexer, out *StatisticsSliceDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "statistics":
			if in.IsNull() {
				in.Skip()
				out.Statistics = nil
			} else {
				in.Delim('[')
				if out.Statistics == nil {
					if !in.IsDelim(']') {
						out.Statistics = make([]StatisticsDTO, 0, 0)
					} else {
						out.Statistics = []StatisticsDTO{}
					}
				} else {
					out.Statistics = (out.Statistics)[:0]
				}
				for !in.IsDelim(']') {
					var v1 StatisticsDTO
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Statistics = append(out.Statistics, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd10493EncodeS21RogueInternalDomainDto(out *jwriter.Writer, in StatisticsSliceDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"statistics\":"
		out.RawString(prefix[1:])
		if in.Statistics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Statistics {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatisticsSliceDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd10493EncodeS21RogueInternalDomainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatisticsSliceDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd10493EncodeS21RogueInternalDomainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatisticsSliceDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd10493DecodeS21RogueInternalDomainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatisticsSliceDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd10493DecodeS21RogueInternalDomainDto(l, v)
}
func easyjsonCd10493DecodeS21RogueInternalDomainDto1(in *jlexer.Lexer, out *StatisticsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "uuid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Id = string(in.String())
			}
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = int(in.Int())
			}
		case "monster_dead":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MonsterDead = int(in.Int())
			}
		case "given_damage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GivenDamage = int(in.Int())
			}
		case "recieved_damage":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RecievedDamage = int(in.Int())
			}
		case "food_eaten":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FoodEaten = int(in.Int())
			}
		case "elixirs_drunk":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ElixirsDrunk = int(in.Int())
			}
		case "scrolls_read":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScrollsRead = int(in.Int())
			}
		case "treasure_found":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TreasureFound = int(in.Int())
			}
		case "stepped_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SteppedCount = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCd10493EncodeS21RogueInternalDomainDto1(out *jwriter.Writer, in StatisticsDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Id))
	}
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix)
		out.Int(int(in.Level))
	}
	{
		const prefix string = ",\"monster_dead\":"
		out.RawString(prefix)
		out.Int(int(in.MonsterDead))
	}
	{
		const prefix string = ",\"given_damage\":"
		out.RawString(prefix)
		out.Int(int(in.GivenDamage))
	}
	{
		const prefix string = ",\"recieved_damage\":"
		out.RawString(prefix)
		out.Int(int(in.RecievedDamage))
	}
	{
		const prefix string = ",\"food_eaten\":"
		out.RawString(prefix)
		out.Int(int(in.FoodEaten))
	}
	{
		const prefix string = ",\"elixirs_drunk\":"
		out.RawString(prefix)
		out.Int(int(in.ElixirsDrunk))
	}
	{
		const prefix string = ",\"scrolls_read\":"
		out.RawString(prefix)
		out.Int(int(in.ScrollsRead))
	}
	{
		const prefix string = ",\"treasure_found\":"
		out.RawString(prefix)
		out.Int(int(in.TreasureFound))
	}
	{
		const prefix string = ",\"stepped_count\":"
		out.RawString(prefix)
		out.Int(int(in.SteppedCount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatisticsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCd10493EncodeS21RogueInternalDomainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatisticsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCd10493EncodeS21RogueInternalDomainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatisticsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCd10493DecodeS21RogueInternalDomainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatisticsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCd10493DecodeS21RogueInternalDomainDto1(l, v)
}
